In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("customer_encoder.csv")
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        50 non-null     int64
 1   review     50 non-null     object
 2   education  50 non-null     object
 3   purchased  50 non-null     object
 4   color      50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

    age   review education purchased  color
0    30  Average    School        No    Red
1    68     Poor        UG        No   Blue
2    70     Good        PG        No  Green
3    72     Good        PG        No    Red
4    16  Average        UG        No   Blue
5    31  Average    School       Yes  Green
6    18     Good    School        No    Red
7    60     Poor    School       Yes   Blue
8    65  Average        UG        No  Green
9    74     Good        UG       Yes    Red
10   98     Good        UG       Yes   Blue
11   74     Good        UG       Yes  Green
12   51     Poor    School        No    Red
13   57  Average    School        No   Blue
14   15     Poor        PG       Yes  Green
15   75     Poor        UG        No    Red
16   59     Poor        UG       Yes   Blue
17   22     Poor        UG       Yes  Green
18   19     Good    School        No    Red
19   97     Poor        PG       Yes   Blue
20   57  Average    School       Yes  Green
21   32  Average        PG        No    Red
22   18     Poor        PG       Yes   Blue
23   96     Good    School        No  Green
24   16  Average        PG       Yes    Red
25   57     Good    School        No   Blue
26   53     Poor        PG        No  Green
27   69     Poor        PG        No    Red
28   48     Poor    School        No   Blue
29   83  Average        UG       Yes  Green
30   73  Average        UG        No    Red
31   22     Poor    School       Yes   Blue
32   92  Average        UG       Yes  Green
33   89     Good        PG       Yes    Red
34   86  Average    School        No   Blue
35   74     Poor    School       Yes  Green
36   34     Good        UG       Yes    Red
37   94  Average        PG       Yes   Blue
38   45     Good    School        No  Green
39   76     Poor        PG        No    Red
40   39     Good    School        No   Blue
41   23     Good        PG       Yes  Green
42   30     Good        PG       Yes    Red
43   27     Poor        PG        No   Blue
44   77  Average        UG        No  Green
45   61     Poor        PG       Yes    Red
46   64     Poor        PG        No   Blue
47   38     Good        PG       Yes  Green
48   39     Good        UG       Yes    Red
49   25     Good        UG        No   Blue

In [3]:
# encoders
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder, OneHotEncoder

In [9]:
df

    age   review education purchased  color
0    30  Average    School        No    Red
1    68     Poor        UG        No   Blue
2    70     Good        PG        No  Green
3    72     Good        PG        No    Red
4    16  Average        UG        No   Blue
5    31  Average    School       Yes  Green
6    18     Good    School        No    Red
7    60     Poor    School       Yes   Blue
8    65  Average        UG        No  Green
9    74     Good        UG       Yes    Red
10   98     Good        UG       Yes   Blue
11   74     Good        UG       Yes  Green
12   51     Poor    School        No    Red
13   57  Average    School        No   Blue
14   15     Poor        PG       Yes  Green
15   75     Poor        UG        No    Red
16   59     Poor        UG       Yes   Blue
17   22     Poor        UG       Yes  Green
18   19     Good    School        No    Red
19   97     Poor        PG       Yes   Blue
20   57  Average    School       Yes  Green
21   32  Average        PG        No    Red
22   18     Poor        PG       Yes   Blue
23   96     Good    School        No  Green
24   16  Average        PG       Yes    Red
25   57     Good    School        No   Blue
26   53     Poor        PG        No  Green
27   69     Poor        PG        No    Red
28   48     Poor    School        No   Blue
29   83  Average        UG       Yes  Green
30   73  Average        UG        No    Red
31   22     Poor    School       Yes   Blue
32   92  Average        UG       Yes  Green
33   89     Good        PG       Yes    Red
34   86  Average    School        No   Blue
35   74     Poor    School       Yes  Green
36   34     Good        UG       Yes    Red
37   94  Average        PG       Yes   Blue
38   45     Good    School        No  Green
39   76     Poor        PG        No    Red
40   39     Good    School        No   Blue
41   23     Good        PG       Yes  Green
42   30     Good        PG       Yes    Red
43   27     Poor        PG        No   Blue
44   77  Average        UG        No  Green
45   61     Poor        PG       Yes    Red
46   64     Poor        PG        No   Blue
47   38     Good        PG       Yes  Green
48   39     Good        UG       Yes    Red
49   25     Good        UG        No   Blue

In [8]:
# ordinal encoder
x = df.iloc[:,1:3]
le = OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])
xx = le.fit_transform(x)
xx

array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

In [5]:
# label encoder
lle = LabelEncoder()
lle.fit_transform(df["purchased"])

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [6]:
# onehotencoder
y = df.iloc[:,-1].values.reshape(-1,1)
ohe = OneHotEncoder()
xx = ohe.fit_transform(y).toarray()