In [2]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv("enron_spam_data.csv",encoding="latin-1")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33716 entries, 0 to 33715
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Message ID  33716 non-null  int64
 1   Subject     33427 non-null  object
 2   Message     33345 non-null  object
 3   Spam/Ham    33716 non-null  object
 4   Date        33716 non-null  object
dtypes: int64(1), object(4)
memory usage: 1.3+ MB

In [4]:
df = df.drop(columns=["Message ID","Date"])
df

,Subject,Message,Spam/Ham
0,christmas tree farm pictures,NaN,ham
1,"vastar resources , inc .","gary , production from the high island larger ...",ham
2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,ham
3,re : issue,fyi - see note below - already done .\nstella\...,ham
4,meter 7268 nov allocation,fyi .\n- - - - - - - - - - - - - - - - - - - -...,ham
...,...,...,...
33711,= ? iso - 8859 - 1 ? q ? good _ news _ c = eda...,"hello , welcome to gigapharm onlinne shop .\np...",spam
33712,all prescript medicines are on special . to be...,i got it earlier than expected and it was wrap...,spam
33713,the next generation online pharmacy .,are you ready to rock on ? let the man in you ...,spam
33714,bloow in 5 - 10 times the time,learn how to last 5 - 10 times longer in\nbed ...,spam
33715,"dear sir , i am interested in it",hi : )\ndo you need some softwares ? i can giv...,spam

In [5]:
le = LabelEncoder()
df["Spam/Ham"] = le.fit_transform(df["Spam/Ham"])

In [6]:
df

,Subject,Message,Spam/Ham
0,christmas tree farm pictures,NaN,0
1,"vastar resources , inc .","gary , production from the high island larger ...",0
2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,0
3,re : issue,fyi - see note below - already done .\nstella\...,0
4,meter 7268 nov allocation,fyi .\n- - - - - - - - - - - - - - - - - - - -...,0
...,...,...,...
33711,= ? iso - 8859 - 1 ? q ? good _ news _ c = eda...,"hello , welcome to gigapharm onlinne shop .\np...",1
33712,all prescript medicines are on special . to be...,i got it earlier than expected and it was wrap...,1
33713,the next generation online pharmacy .,are you ready to rock on ? let the man in you ...,1
33714,bloow in 5 - 10 times the time,learn how to last 5 - 10 times longer in\nbed ...,1
33715,"dear sir , i am interested in it",hi : )\ndo you need some softwares ? i can giv...,1

In [8]:
import numpy as np

In [22]:
df = df.dropna(subset=["Subject"])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 33345 entries, 1 to 33715
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Subject   33107 non-null  object
 1   Message   33345 non-null  object
 2   Spam/Ham  33345 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

In [17]:
df

,Subject,Message,Spam/Ham
1,"vastar resources , inc .","gary , production from the high island larger ...",0
2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc,0
3,re : issue,fyi - see note below - already done .\nstella\...,0
4,meter 7268 nov allocation,fyi .\n- - - - - - - - - - - - - - - - - - - -...,0
5,mcmullen gas for 11 / 99,"jackie ,\nsince the inlet to 3 river plant is ...",0
...,...,...,...
33711,= ? iso - 8859 - 1 ? q ? good _ news _ c = eda...,"hello , welcome to gigapharm onlinne shop .\np...",1
33712,all prescript medicines are on special . to be...,i got it earlier than expected and it was wrap...,1
33713,the next generation online pharmacy .,are you ready to rock on ? let the man in you ...,1
33714,bloow in 5 - 10 times the time,learn how to last 5 - 10 times longer in\nbed ...,1
33715,"dear sir , i am interested in it",hi : )\ndo you need some softwares ? i can giv...,1

In [18]:
x = df.iloc[:,:2]
y = df.iloc[:,-1]
x

,Subject,Message
1,"vastar resources , inc .","gary , production from the high island larger ..."
2,calpine daily gas nomination,- calpine daily gas nomination 1 . doc
3,re : issue,fyi - see note below - already done .\nstella\...
4,meter 7268 nov allocation,fyi .\n- - - - - - - - - - - - - - - - - - - -...
5,mcmullen gas for 11 / 99,"jackie ,\nsince the inlet to 3 river plant is ..."
...,...,...
33711,= ? iso - 8859 - 1 ? q ? good _ news _ c = eda...,"hello , welcome to gigapharm onlinne shop .\np..."
33712,all prescript medicines are on special . to be...,i got it earlier than expected and it was wrap...
33713,the next generation online pharmacy .,are you ready to rock on ? let the man in you ...
33714,bloow in 5 - 10 times the time,learn how to last 5 - 10 times longer in\nbed ...
33715,"dear sir , i am interested in it",hi : )\ndo you need some softwares ? i can giv...

In [24]:
v = CountVectorizer()
x_v = v.fit_transform(df["Message"],df["Subject"])
print(x_v)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3876043 stored elements and shape (33107, 153072)>
  Coords	Values
  (0, 61454)	2
  (0, 109819)	3
  (0, 60141)	3
  (0, 134097)	8
  (0, 68102)	2
  (0, 75617)	2
  (0, 82306)	2
  (0, 27023)	2
  (0, 36730)	1
  (0, 100170)	7
  (0, 121005)	1
  (0, 21448)	3
  (0, 0)	2
  (0, 13979)	1
  (0, 7961)	4
  (0, 64818)	3
  (0, 31611)	3
  (0, 55052)	2
  (0, 25656)	1
  (0, 18413)	4
  (0, 1023)	11
  (0, 1)	18
  (0, 58954)	3
  (0, 135991)	4
  (0, 142122)	5
  :	:
  (33106, 63037)	1
  (33106, 145916)	1
  (33106, 95892)	1
  (33106, 7960)	1
  (33106, 111272)	1
  (33106, 36504)	1
  (33106, 92945)	1
  (33106, 134019)	1
  (33106, 142834)	2
  (33106, 134235)	1
  (33106, 43571)	1
  (33106, 144991)	1
  (33106, 69899)	1
  (33106, 33597)	1
  (33106, 84380)	1
  (33106, 47659)	1
  (33106, 32449)	1
  (33106, 125255)	1
  (33106, 110000)	1
  (33106, 110027)	1
  (33106, 107775)	1
  (33106, 86163)	1
  (33106, 126617)	1
  (33106, 152274)	1
  (33106, 126628)	1

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x_v,y,test_size=0.2,random_state=33)

ValueError: Found input variables with inconsistent numbers of samples: [33107, 33345]